### ISSUE TITLE
Convert to imperial

### ISSUE THREAD

**Issue by Callindrill** [Cellule/dndGenerator#4]
An option to convert to imperial would be nice so that I don't have to do it by hand every time.

**Comment by Cellule** [comment]
I am not familiar with Imperial, can you give me a link with more info ?

**Comment by etiens** [comment]
He means Feet/Inches instead of cm/m. I hadn't done it initially because it would have taken too long for not much, and you'd have to click the button to translate anyway, so in the end you wouldn't even end up saving that much time.  
I'll see if I can do it. It's just that my time on the project is very limited. Right now I'm adding some new races and plot hooks to choose from, and I just think that overall spending my time on stuff like that would be more useful and entertaining to people using my site than a imperial/metric translator. After I'm done with my current work I'll see if it wouldn't be too much trouble!

**Comment by Cellule** [comment]
> He means Feet/Inches instead of cm/m

Right... I was just too focused on converting the file export

**Comment by Cellule** [comment]
Is this only for the height or are there other places we use measurement units ?

**Comment by etiens** [comment]
It should be only for the height

**Comment by Callindrill** [comment]
I was thinking that it would be something like a slider/checkbox for the output--sort of like the settings on the side. If it ends up being easy, it would be a nice get, if not, it's fine. Without it, I can't use it as an "on the fly" generator, though, as none of my players are familiar with metric units. 

I also wouldn't mind taking a look at the code base to do it myself, if I got time--not sure how amiable you are to pull requests.

**Comment by etiens** [comment]
Having it as an option was a bit complicated because of the way the system is set up, for now both units are displayed in the NPC description!! I think this will be helpful to a lot of people!

**Comment by Callindrill** [comment]
There is an error with the rounding. I am not super familiar with this language in particular (and the weakly typed cars in the toFeet function don't help), but I think your Round function is receiving an int instead of a float/decimal, resulting in off by one errors. You can use 182 cm to test as it is 5ft 11.6... inches.
